import {
    amber,
    blue,
    blueGrey,
    brown,
    cyan,
    deepOrange,
    deepPurple,
    green,
    grey,
    indigo,
    lightBlue,
    lightGreen,
    lime,
    orange,
    pink,
    purple,
    red,
    teal,
    yellow,
} from '@mui/material/colors';

export const Colors:any = {
    "amber": amber[500],
    "blue": blue[500],
    "blueGrey": blueGrey[500],
    "brown": brown[500],
    "cyan": cyan[500],
    "deepOrange": deepOrange[500],
    "deepPurple": deepPurple[500],
    "green": green[500],
    "grey": grey[500],
    "indigo": indigo[500],
    "lightBlue": lightBlue[500],
    "lightGreen": lightGreen[500],
    "lime": lime[500],
    "orange": orange[500],
    "pink": pink[500],
    "purple": purple[500],
    "red": red[500],
    "teal": teal[500],
    "yellow": yellow[500],
}